const { Pool } = require('pg');
const fs = require('fs');
require('dotenv').config();

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false }
});

async function main() {
  let report = '';
  const logMsg = (msg) => {
    console.log(msg);
    report += msg + '\n';
  };

  try {
    const logsRes = await pool.query(`
      SELECT id, status, log_output, executed_at 
      FROM cloud_tasks_logs 
      ORDER BY id ASC;
    `);

    logMsg('=== LOGS PARSING SUMMARY ===');
    const processedCounts = {};
    
    for (const log of logsRes.rows) {
      if (!log.log_output) continue;
      const regex = /PROCESANDO CLIENTE \(\d+\/\d+\):\s*([^\s@]+)@s\.whatsapp\.net/g;
      let match;
      while ((match = regex.exec(log.log_output)) !== null) {
        const number = match[1];
        if (!processedCounts[number]) {
          processedCounts[number] = [];
        }
        processedCounts[number].push({
          logId: log.id,
          executedAt: log.executed_at,
          status: log.status
        });
      }
    }

    let repeatedFound = false;
    for (const [number, occurrences] of Object.entries(processedCounts)) {
      if (occurrences.length > 1) {
        repeatedFound = true;
        logMsg(`❌ Repetition found: Number +${number} was processed ${occurrences.length} times:`);
        occurrences.forEach(o => {
          logMsg(`   - Log ID: ${o.logId} | Executed: ${o.executedAt.toISOString()} | Status: ${o.status}`);
        });
      }
    }
    
    if (!repeatedFound) {
      logMsg('✅ No repeated numbers found in logs.');
    }

    // Let's also check if there are actual messages sent in dinastia_chat_histories that look like duplicates.
    logMsg('\n=== REPETITIVE MESSAGES IN DINASTIA_CHAT_HISTORIES ===');
    const historyRes = await pool.query(`
      SELECT session_id, message::text as msg_str, created_at
      FROM dinastia_chat_histories
      ORDER BY created_at ASC;
    `);
    
    const messagesBySession = {};
    for (const row of historyRes.rows) {
      const number = row.session_id.split('@')[0];
      let msg;
      try {
        msg = JSON.parse(row.msg_str);
      } catch (e) {
        continue;
      }
      
      // We look for AI or ASESOR messages
      if (msg.type === 'ai' || msg.type === 'asesor') {
        if (!messagesBySession[number]) {
          messagesBySession[number] = [];
        }
        messagesBySession[number].push({
          content: msg.content,
          createdAt: row.created_at,
          type: msg.type
        });
      }
    }

    for (const [number, msgs] of Object.entries(messagesBySession)) {
      // Find consecutive AI/asesor messages without human intervention
      let consecutiveCount = 0;
      let lastType = null;
      let consecutiveMsgs = [];
      
      for (const m of msgs) {
        if (m.type === 'ai' || m.type === 'asesor') {
          consecutiveCount++;
          consecutiveMsgs.push(m);
        } else {
          // Reset if there is human message (but here we only queried AI/asesor, so we need to query ALL messages per session to check consecutive)
        }
      }
    }

    // Let's do a proper search for consecutive AI/asesor messages
    const allHistoryRes = await pool.query(`
      SELECT session_id, message::text as msg_str, created_at
      FROM dinastia_chat_histories
      ORDER BY session_id, created_at ASC;
    `);

    const sessionsData = {};
    for (const row of allHistoryRes.rows) {
      const session = row.session_id;
      let msg;
      try {
        msg = JSON.parse(row.msg_str);
      } catch (e) {
        continue;
      }
      if (!sessionsData[session]) {
        sessionsData[session] = [];
      }
      sessionsData[session].push({
        type: msg.type,
        content: msg.content,
        createdAt: row.created_at
      });
    }

    logMsg('\nSessions with consecutive AI/ASESOR follow-ups (more than 1 in a row without HUMAN response):');
    for (const [session, msgs] of Object.entries(sessionsData)) {
      let consecutiveAi = [];
      for (const m of msgs) {
        if (m.type === 'ai' || m.type === 'asesor') {
          // Check if this was generated by our followup task
          // We can check if it says something like "¡Hola!..." or has specific phrases
          consecutiveAi.push(m);
        } else if (m.type === 'human') {
          if (consecutiveAi.length > 1) {
            logMsg(`Session: ${session} had ${consecutiveAi.length} consecutive AI/asesor messages before client replied:`);
            consecutiveAi.forEach(c => {
              logMsg(`  - [${c.createdAt.toISOString()}] ${c.type}: "${c.content ? c.content.substring(0, 100).replace(/\n/g, ' ') : ''}"`);
            });
          }
          consecutiveAi = [];
        }
      }
      // If at the end of the history, they still have consecutive AI messages
      if (consecutiveAi.length > 1) {
        logMsg(`Session: ${session} ended with ${consecutiveAi.length} consecutive AI/asesor messages without reply:`);
        consecutiveAi.forEach(c => {
          logMsg(`  - [${c.createdAt.toISOString()}] ${c.type}: "${c.content ? c.content.substring(0, 100).replace(/\n/g, ' ') : ''}"`);
        });
      }
    }

    fs.writeFileSync('repetitions_report.txt', report);
    console.log('Report written to repetitions_report.txt');

  } catch (err) {
    console.error('Error:', err);
  } finally {
    await pool.end();
  }
}

main();
